apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: prod-solar-app-vso-secret
  namespace: prod-solar-app
spec:
  vaultAuthRef: prod-solar-app-vso-auth
  mount: secrets
  type: kv-v2
  path: prod-solar-app/mongo-url   # Path inside Vault
  refreshAfter: 60s
  destination:
    name: mongo-uri # This is the REAL K8s Secret that will appear
    create: true