apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storage-classes-argocd-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: "https://github.com/automation-handson/solar-gitops.git"
    targetRevision: main
    path: argocd/k8s-apps/storage-classes
  destination:
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true