apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-argocd-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "9"
spec:
  project: default
  sources:
    - repoURL: "https://charts.jenkins.io"
      targetRevision: 5.9.0
      chart: jenkins
      helm:
        releaseName: jenkins
        valueFiles:
          - $jenkins-values/argocd/k8s-apps/jenkins/jenkins-values.yaml
    - repoURL: "https://github.com/automation-handson/solar-gitops.git"
      targetRevision: main
      path: argocd/k8s-apps/jenkins
      ref: jenkins-values  
  destination:
    server: "https://kubernetes.default.svc"
    namespace: jenkins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true