apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: solar-app-of-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/automation-handson/solar-gitops.git"
    targetRevision: main
    path: argocd/argocd-apps
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true